services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: siakad
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  dbdata: